// <auto-generated />
using System;
using InmobiliariaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InmobiliariaApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251026033612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InmobiliariaApi.Models.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdInmueble")
                        .HasColumnType("int");

                    b.Property<int>("IdInquilino")
                        .HasColumnType("int");

                    b.Property<int?>("InmuebleIdInmueble")
                        .HasColumnType("int");

                    b.Property<int?>("InquilinoIdInquilino")
                        .HasColumnType("int");

                    b.Property<double>("MontoAlquiler")
                        .HasColumnType("double");

                    b.HasKey("IdContrato");

                    b.HasIndex("InmuebleIdInmueble");

                    b.HasIndex("InquilinoIdInquilino");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("InmobiliariaApi.Models.Inmueble", b =>
                {
                    b.Property<int>("IdInmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInmueble"));

                    b.Property<int>("Ambientes")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<bool>("Disponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DuenioIdPropietario")
                        .HasColumnType("int");

                    b.Property<int>("IdPropietario")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .HasColumnType("longtext");

                    b.Property<double>("Latitud")
                        .HasColumnType("double");

                    b.Property<double>("Longitud")
                        .HasColumnType("double");

                    b.Property<int>("Superficie")
                        .HasColumnType("int");

                    b.Property<bool>("TieneContratoVigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("Uso")
                        .HasColumnType("longtext");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("IdInmueble");

                    b.HasIndex("DuenioIdPropietario");

                    b.ToTable("Inmuebles");
                });

            modelBuilder.Entity("InmobiliariaApi.Models.Inquilino", b =>
                {
                    b.Property<int>("IdInquilino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInquilino"));

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("IdInquilino");

                    b.ToTable("Inquilinos");
                });

            modelBuilder.Entity("InmobiliariaApi.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<int?>("ContratoIdContrato")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdContrato")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdPago");

                    b.HasIndex("ContratoIdContrato");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("InmobiliariaApi.Models.Propietario", b =>
                {
                    b.Property<int>("IdPropietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPropietario"));

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Clave")
                        .HasColumnType("longtext");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("IdPropietario");

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("InmobiliariaApi.Models.Contrato", b =>
                {
                    b.HasOne("InmobiliariaApi.Models.Inmueble", "Inmueble")
                        .WithMany()
                        .HasForeignKey("InmuebleIdInmueble");

                    b.HasOne("InmobiliariaApi.Models.Inquilino", "Inquilino")
                        .WithMany()
                        .HasForeignKey("InquilinoIdInquilino");

                    b.Navigation("Inmueble");

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("InmobiliariaApi.Models.Inmueble", b =>
                {
                    b.HasOne("InmobiliariaApi.Models.Propietario", "Duenio")
                        .WithMany()
                        .HasForeignKey("DuenioIdPropietario");

                    b.Navigation("Duenio");
                });

            modelBuilder.Entity("InmobiliariaApi.Models.Pago", b =>
                {
                    b.HasOne("InmobiliariaApi.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoIdContrato");

                    b.Navigation("Contrato");
                });
#pragma warning restore 612, 618
        }
    }
}
